name: 'Gitbook Build'
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gitbook Action
        uses: ZanderZhao/gitbook-action@master
        with:
          token: ${{ secrets.TOKEN }}
